/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.4.1-240
 *
 */
import { Fluence, FluencePeer } from '@fluencelabs/fluence';
import {
    CallParams,
    callFunction,
    registerService,
} from '@fluencelabs/fluence/dist/internal/compilerSupport/v2';


// Services
export interface ListenerDef {
    receiveData: (packet: { data: string; type: string; }, callParams: CallParams<'packet'>) => void | Promise<void>;
}
export function registerListener(service: ListenerDef): void;
export function registerListener(serviceId: string, service: ListenerDef): void;
export function registerListener(peer: FluencePeer, service: ListenerDef): void;
export function registerListener(peer: FluencePeer, serviceId: string, service: ListenerDef): void;
       

// Functions

